remote_theme: pages-themes/midnight@v0.2.0
url: "https://kozyakin.github.io" # the base hostname & protocol for your site
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap
